# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9641796da97e762b637a9d3dbf48d0bd5ddd4aa826f9d73f7af238c61f9d5449739fce69e364a55969c10d18b86f9130134abb36babbcf22718d84833899d7bf

test:
  secret_key_base: b85ff13f18f07641d954757faee03c48d7acf451c4e5c44890812ffea83d20fe558069a55a01987e473269c340fa945a492f4a0efecc1e2bc75e86f20bfd0396

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
